//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWiNFO_Transfer_to_LCD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HWiNFO64")]
        public string HWiNFO_PROCCESS_NAME {
            get {
                return ((string)(this["HWiNFO_PROCCESS_NAME"]));
            }
            set {
                this["HWiNFO_PROCCESS_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HWiNFOTransferToLCD")]
        public string SysLogSourceName {
            get {
                return ((string)(this["SysLogSourceName"]));
            }
            set {
                this["SysLogSourceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HWiNFO Transfer")]
        public string SysLogName {
            get {
                return ((string)(this["SysLogName"]));
            }
            set {
                this["SysLogName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM5")]
        public string SerialPortName {
            get {
                return ((string)(this["SerialPortName"]));
            }
            set {
                this["SerialPortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int SerialPortSpeed {
            get {
                return ((int)(this["SerialPortSpeed"]));
            }
            set {
                this["SerialPortSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16777470")]
        public uint CPUPackageTempID {
            get {
                return ((uint)(this["CPUPackageTempID"]));
            }
            set {
                this["CPUPackageTempID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint CPUPackageTempIndex {
            get {
                return ((uint)(this["CPUPackageTempIndex"]));
            }
            set {
                this["CPUPackageTempIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("117440529")]
        public uint TotalCPUUsageID {
            get {
                return ((uint)(this["TotalCPUUsageID"]));
            }
            set {
                this["TotalCPUUsageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint TotalCPUUsageIndex {
            get {
                return ((uint)(this["TotalCPUUsageIndex"]));
            }
            set {
                this["TotalCPUUsageIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83886080")]
        public uint CPUPackagePowerID {
            get {
                return ((uint)(this["CPUPackagePowerID"]));
            }
            set {
                this["CPUPackagePowerID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public uint CPUPackagePowerIndex {
            get {
                return ((uint)(this["CPUPackagePowerIndex"]));
            }
            set {
                this["CPUPackagePowerIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50331651")]
        public uint CPUFanID {
            get {
                return ((uint)(this["CPUFanID"]));
            }
            set {
                this["CPUFanID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public uint CPUFanIndex {
            get {
                return ((uint)(this["CPUFanIndex"]));
            }
            set {
                this["CPUFanIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public uint GPUIndex {
            get {
                return ((uint)(this["GPUIndex"]));
            }
            set {
                this["GPUIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16777216")]
        public uint GPUTempID {
            get {
                return ((uint)(this["GPUTempID"]));
            }
            set {
                this["GPUTempID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("117440512")]
        public uint GPUCoreLoadID {
            get {
                return ((uint)(this["GPUCoreLoadID"]));
            }
            set {
                this["GPUCoreLoadID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("117440520")]
        public uint GPUMemoryUsageID {
            get {
                return ((uint)(this["GPUMemoryUsageID"]));
            }
            set {
                this["GPUMemoryUsageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83886080")]
        public uint GPUPowerID {
            get {
                return ((uint)(this["GPUPowerID"]));
            }
            set {
                this["GPUPowerID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50331648")]
        public uint GPUFanID {
            get {
                return ((uint)(this["GPUFanID"]));
            }
            set {
                this["GPUFanID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("134217733")]
        public uint MemoryUsageID {
            get {
                return ((uint)(this["MemoryUsageID"]));
            }
            set {
                this["MemoryUsageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint MemoryUsageIndex {
            get {
                return ((uint)(this["MemoryUsageIndex"]));
            }
            set {
                this["MemoryUsageIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16777216")]
        public uint DIMM_0_TemperatureID {
            get {
                return ((uint)(this["DIMM_0_TemperatureID"]));
            }
            set {
                this["DIMM_0_TemperatureID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public uint DIMM_0_TemperatureIndex {
            get {
                return ((uint)(this["DIMM_0_TemperatureIndex"]));
            }
            set {
                this["DIMM_0_TemperatureIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16777218")]
        public uint DIMM_2_TemperatureID {
            get {
                return ((uint)(this["DIMM_2_TemperatureID"]));
            }
            set {
                this["DIMM_2_TemperatureID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public uint DIMM_2_TemperatureIndex {
            get {
                return ((uint)(this["DIMM_2_TemperatureIndex"]));
            }
            set {
                this["DIMM_2_TemperatureIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("134217728")]
        public uint PSUPowerEfficiencyID {
            get {
                return ((uint)(this["PSUPowerEfficiencyID"]));
            }
            set {
                this["PSUPowerEfficiencyID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public uint PSUPowerEfficiencyIndex {
            get {
                return ((uint)(this["PSUPowerEfficiencyIndex"]));
            }
            set {
                this["PSUPowerEfficiencyIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83886090")]
        public uint PSUPowerID {
            get {
                return ((uint)(this["PSUPowerID"]));
            }
            set {
                this["PSUPowerID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public uint PSUPowerIndex {
            get {
                return ((uint)(this["PSUPowerIndex"]));
            }
            set {
                this["PSUPowerIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16777216")]
        public uint PSUTemperatureID {
            get {
                return ((uint)(this["PSUTemperatureID"]));
            }
            set {
                this["PSUTemperatureID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public uint PSUTemperatureIndex {
            get {
                return ((uint)(this["PSUTemperatureIndex"]));
            }
            set {
                this["PSUTemperatureIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16777216")]
        public uint DiskTempID {
            get {
                return ((uint)(this["DiskTempID"]));
            }
            set {
                this["DiskTempID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public uint Disk1TempIndex {
            get {
                return ((uint)(this["Disk1TempIndex"]));
            }
            set {
                this["Disk1TempIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public uint Disk2TempIndex {
            get {
                return ((uint)(this["Disk2TempIndex"]));
            }
            set {
                this["Disk2TempIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public uint Disk3TempIndex {
            get {
                return ((uint)(this["Disk3TempIndex"]));
            }
            set {
                this["Disk3TempIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("134217728")]
        public uint DiskReadID {
            get {
                return ((uint)(this["DiskReadID"]));
            }
            set {
                this["DiskReadID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("134217729")]
        public uint DiskWriteID {
            get {
                return ((uint)(this["DiskWriteID"]));
            }
            set {
                this["DiskWriteID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public uint Disk1SpeedID {
            get {
                return ((uint)(this["Disk1SpeedID"]));
            }
            set {
                this["Disk1SpeedID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public uint Disk2SpeedID {
            get {
                return ((uint)(this["Disk2SpeedID"]));
            }
            set {
                this["Disk2SpeedID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public uint Disk3SpeedID {
            get {
                return ((uint)(this["Disk3SpeedID"]));
            }
            set {
                this["Disk3SpeedID"] = value;
            }
        }
    }
}
